################################### Chinese language #####################################
[zh]
languageName = "简中"
#languageCode = "zh_CN"
contentDir = "content/simplified"
staticDir = "static"
weight = 1
footer_content = "专注于 DevSecOps, 发现并解决应用安全风险"
# copyright
copyright = ""

################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
#footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = ""
