############# Chinese navigation ##############
# main menu
[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "文档"
url = "https://doc.dongtai.io/index.html"
weight = 2

#[[main]]
#name = "最新消息"
#url = "news/"
#weight = 3

#[[main]]
#name = "博客"
#url = "blog/"
#weight = 4

[[main]]
name = "更新亮点"
url = "changelog/"
weight = 5

[[main]]
#name = "Contact"
#url = "contact/"
#weight = 6

[[main]]
#name = "Pages"
#weight = 7
#hasChildren = false

  [[main]]
  #parent = "Pages"
  #name = "Career"
  #url = "career/"

  [[main]]
  #parent = "Pages"
  #name = "Pricing"
  #url = "pricing/"

  [[main]]
  #parent = "Pages"
  #name = "Pricing 2"
  #url = "pricing-2/"
  
  [[main]]
  #parent = "Pages"
  #name = "How It Works"
  #url = "how-it-works/"
  
  [[main]]
  #parent = "Pages"
  #name = "Testimonial"
  #url = "testimonial/"
  
  [[main]]
  #parent = "Pages"
  #name = "Faq"
  #url = "faq/"
  
  [[main]]
  #parent = "Pages"
  #name = "Changelog"
  #url = "changelog/"

# Footer menu
[[footer]]
name = "Docs"
url = "https://doc.dongtai.io"
weight = 1

[[footer]]
name = "FAQ"
url = "https://doc.dongtai.io/09_faq/index.html"
weight = 2

#[[footer]]
#name = "Terms & Conditions"
#url = "terms-conditions/"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3