[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"